### PR TITLE
Development

### PR DESCRIPTION
**Pull request by ash10x**
- changes to navigation 
- added company name in footer

### CODE REVIEW

**Comment by rmcdonald01** [comment]
Is this what we spoke about yesterday?

**Comment by ash10x** [comment]
> Is this what we spoke about yesterday?

yeah

**Comment by ash10x** [comment]
laravel

**Comment by ash10x** [comment]
Worked on mobile!

**Comment by rmcdonald01** [comment]
> Worked on mobile!

Interesting

**Comment by rmcdonald01** [comment]
Merge completed

**Pull request merged**
